/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminDashboard: typeof import('./src/components/AdminDashboard.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    CitasList: typeof import('./src/components/CitasList.vue')['default']
    EmpresaDashboard: typeof import('./src/components/EmpresaDashboard.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeView: typeof import('./src/components/HomeView.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    RegisterEmpresaForm: typeof import('./src/components/RegisterEmpresaForm.vue')['default']
    RegisterForm: typeof import('./src/components/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceList: typeof import('./src/components/ServiceList.vue')['default']
    UserDashboard: typeof import('./src/components/UserDashboard.vue')['default']
    UserProfile: typeof import('./src/components/UserProfile.vue')['default']
  }
}
